### ISSUE TITLE
3.2 broke it again :(

### ISSUE THREAD

**Issue by chucker** [Lupusa87/BlazorWebSocketHelper#3]
It looks like https://github.com/dotnet/aspnetcore/pull/17942 broke the JS. Stuff like `Blazor.platform.findMethod` no longer exists.

**Comment by Lupusa87** [comment]
Hello, sorry I have not time for last 6 months to code any blazor.
If you will make pull request I will merge it for sure.

**Comment by chucker** [comment]
Hey,

that's OK. I started working on a pull request, but a lot of low-level stuff needed to be changed.

I then realized it's now possible to reference the NuGet package `System.Net.WebSockets.Client` from a Blazor WebAssembly project and use that instead. Seems to mostly work.

Thanks a ton for your project, though!

**Comment by Lupusa87** [comment]
@chucker Glad you figured it out.
 Thank you and good luck.
